### ISSUE TITLE
Merge latest updates from Acidanthera

### ISSUE THREAD

**Issue by 1alessandro1** [fischerscode/IntelMausi-WOL#3]
Since the IntelMausi driver was updated few days ago, is it enough to apply changes to `IntelMausiEthernet.cpp` in order to achieve WoL enabled by default?

![image](https://user-images.githubusercontent.com/46293832/104610004-f0778000-5683-11eb-9ebf-acee96a532d8.png)

**Comment by fischerscode** [comment]
It might work for you. I've actually done some additional changes.
All the updates from IntelMausi are merged now.
Since you've created this issue in some month ago (Oops!) I'll close it. Feel free to reopen if needed.

**Comment by 1alessandro1** [comment]
Hi, thanks for replying.

[This commit](https://github.com/acidanthera/IntelMausi/commit/a2078d81a42f3bd8c2a291a0dfacb5f2ead09145#diff-c275fec9c453c2a42515bc5ab47e30fa4130ff1426aef2f6e000a9a34e122cb8R22) should've fixed WoL on the original IntelMausi from acidanthera, (and the master one from Mieze [recieved support](https://github.com/Mieze/IntelMausiEthernet/commit/2a2b9f864e3f9f0ac336ae7d3f2e471fb28b9d2e) as well by now) right?

**Comment by fischerscode** [comment]
As far as I know, WoL from S5 as only been added to the IntelMausiEthernet by enabling it in the [Info.plist](https://github.com/Mieze/IntelMausiEthernet/commit/2a2b9f864e3f9f0ac336ae7d3f2e471fb28b9d2e#diff-2af3b785657190a086e03632d537db35fa256ed1b0e5b43c85f54b1e8f1a9f37) (**not working for me**). For IntelMausi this setting does not seem to exist.

**Comment by 1alessandro1** [comment]
@fischerscode now the wake on lan feature implemented in this fork should be merged into the original project, since [this commit](https://github.com/acidanthera/IntelMausi/commit/7cdb383e4dc346264d1441dfa29e7eab2b9ccbbc) check if the latest IntelMausi works for you, a prebuilt can be found [here](https://github.com/dortania/build-repo/releases/download/IntelMausi-7cdb383/IntelMausi-1.0.7-RELEASE.zip).

To make it work on my build, I first checked if the path for the I219V2 chipset `GLAN` was:

```
PciRoot(0x0)/Pci(0x1F,0x6)
```

And it was, so I added a `DeviceProperty` :

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PciRoot(0x0)/Pci(0x1F,0x6)</key>
	<dict>
		<key>mausi-force-wol</key>
		<data>
		AQ==
		</data>
	</dict>
</dict>
</plist>

```
